INSERT INTO ESTUDIO (ESTUDIO) VALUES ('PARAMOUNT', 'paramount');
INSERT INTO ESTUDIO (ESTUDIO) VALUES ('WARNER BROS.', 'warner_bros');

INSERT INTO GENERO (GENERO, URL) VALUES ('AÇÃO', 'acao');
INSERT INTO GENERO (GENERO, URL) VALUES ('AVENTURA', 'aventura');
INSERT INTO GENERO (GENERO, URL) VALUES ('HISTORIA', 'historia');
INSERT INTO GENERO (GENERO, URL) VALUES ('BIBLIOGRAFICO', 'bibliografico');

INSERT INTO FILME (TITULO, TITULO_ORIGINAL, ANO, DURACAO, SINOPSE, URL) VALUES ('Uma Mente Brilhante', 'A Beautiful Mind', 2001, 120 , 'John Nash é um matemático prolífico e de pensamento não convencional, que consegue sucesso em várias áreas da matemática e uma carreira acadêmica respeitável. Após resolver na década de 1950 um problema relacionado à teoria dos jogos, que lhe renderia, em 1994, o Prêmio de Ciências Econômicas em Memória de Alfred Nobel (não confundir com o Prêmio Nobel), Nash se casa com Alicia. Após ser chamado a fazer um trabalho em criptografia para o governo dos Estados Unidos, Nash passa a ser atormentado por delírios e alucinações. Diagnosticado como esquizofrênico, e após várias internações, ele precisará usar de toda a sua racionalidade para distinguir o real do imaginário e voltar a ter uma vida normal assim como seus amigos.' , 'https://upload.wikimedia.org/wikipedia/pt/b/b1/UmaMenteBrilhante.jpg');
INSERT INTO FILME (TITULO, TITULO_ORIGINAL, ANO, DURACAO, SINOPSE, URL) VALUES ('Alexandria', 'Ágora', 2009, 90, 'Esta obra cinematográfica relata a história de Hipátia, filósofa e professora em Alexandria, no Egito entre os anos 355 e 415 d.C. Única personagem feminina do filme, Hipátia ensina filosofia, matemática e astronomia na Escola de Alexandria, junto à Biblioteca. Resultante de uma cultura iniciada com Alexandre Magno, passando depois pela dominação romana, Alexandria é agitada por ideais religiosos diversos: o cristianismo, convive de forma tensa com o judaísmo e a cultura greco-romana. Hipátia tem entre seus alunos Orestes, que a adora, mas não é correspondido, e Sinésio, adepto do cristianismo. Seu escravo Davus também a ama, secretamente. Hipátia não deseja casar-se, ela se dedica unicamente ao estudo, à filosofia, matemática, astronomia, e sua principal preocupação, no relato do filme, é com o movimento da terra em torno do sol. Mediante os vários enfrentamentos entre cristãos, judeus e a cultura greco-romana, os cristãos se apoderam, aos poucos, da situação, e enquanto Orestes se torna prefeito e se mantém fiel ao seu amor, o ex-escravo Davus (que recebeu a alforria de Hipátia) se debate entre a fé cristã e a paixão. O líder cristão Cirilo de Alexandria domina a cidade e encontra na ligação entre Orestes e Hipátia o ponto de fragilidade do poder romano, iniciando uma campanha de enfraquecimento da influência de Hipátia sobre o prefeito, usando as escrituras sagradas para acusá-la de bruxaria. Por ter se recusado a se converter ao cristianismo, foi acusada de bruxaria. Uma multidão se reúne para mata-la, a esfolando viva. Mas Davus os convence a apedreja-la. Quando a multidão sai para procurar as pedras, Davus sufoca Hipátia, para poupa-la do apedrejamento e diz a multidão que ela desmaiou. Davus se retira quando começam a apedrejar o corpo de Hipátia.', 'https://upload.wikimedia.org/wikipedia/pt/8/81/Agoraposter09.jpg');
INSERT INTO FILME (TITULO, TITULO_ORIGINAL, ANO, DURACAO, SINOPSE, URL) VALUES ('Troia', 'Troy', 2004, 135,  'Em 1193 a.C., o príncipe Páris provocou uma guerra contra Troia ao afastar Helena de seu marido, Menelau. Tem início então uma sangrenta batalha que dura uma década. A esperança do rei Príamo de Troia em vencer a guerra está nas mãos de seus filhos, Heitor que é um grande guerreiro e comanda o exército e de Páris, o mais jovem. Também contam com a forma estratégica como a cidade-estado foi construída, tendo suas muralhas quase intransponíveis pelos adversários. Aquiles, o maior herói da Grécia Antiga em sua época não queria ir pra guerra. Mas seguindo conselhos de sua mãe e instigado por Odisseu, luta ao lado de Menelau. Junto aos seus guerreiros, chamados Mirmidões, está seu primo Pátroclo (que na verdade é seu amigo), mas tem bastante semelhança física com ele. Pode-se dizer que esse jovem teve uma participação muito interessante na história, quando passando-se por Aquiles leva os guerreiros pra uma luta contra os homens de Heitor que o mata. A perda do primo enfureceu Aquiles, que na busca de vingança, desafia Heitor e o mata. No mais segue de acordo com a Ilíada, a construção do cavalo que é levado pra dentro da cidade como um presente de Poseidon, e na verdade é uma grande cilada pois vários soldados estão escondidos em seu interior. São eles que matam os vigias e abrem os portões para a entrada do exército de Menelau.', 'https://upload.wikimedia.org/wikipedia/pt/e/ec/Troia_poster.jpg');
INSERT INTO FILME (TITULO, TITULO_ORIGINAL, ANO, DURACAO, SINOPSE, URL) VALUES ('A Última Legião', 'The Last Legion', 2007, 80, 'Roma, 476 D.C. No dia da cerimônia de coroação do novo imperador Romulus Augustus (Thomas Sangster), de apenas 12 anos, o general bárbaro Odoacer (Peter Mullan) chega a Roma para fazer um acordo com Orestes (Iain Glen), pai de Romulus. Odoacer exige uma recompensa por seu apoio ao império por várias décadas, mas Orestes recusa o acordo. Preocupado com a segurança do filho e com a previsão do xamã Ambrosinus (Ben Kingsley), Orestes coloca Aurelius (Colin Firth), da Quarta Legião, como guarda pessoal do garoto. Naquela mesma noite Odoacer e sua tropa invadem Roma, matando Orestes e capturando Romulus e Ambrosinus, que são levados para a ilha-fortaleza de Capri. No local Romulus encontra a espada mitológica de César, que passa a usar. Paralelamente Aurelius reúne um pequeno exército e parte para resgatar Romulus.', 'https://pt.wikipedia.org/wiki/A_%C3%9Altima_Legi%C3%A3o#/media/Ficheiro:Last_legion.jpg');

INSERT INTO FILME_ESTUDIO (FILME_ID, ESTUDIO_ID) VALUES ('1', '2');
INSERT INTO FILME_ESTUDIO (FILME_ID, ESTUDIO_ID) VALUES ('2', '1');
INSERT INTO FILME_ESTUDIO (FILME_ID, ESTUDIO_ID) VALUES ('3', '2');
INSERT INTO FILME_ESTUDIO (FILME_ID, ESTUDIO_ID) VALUES ('4', '1');

INSERT INTO FILME_GENERO (FILME_ID, GENERO_ID) VALUES ('1', '4');
INSERT INTO FILME_GENERO (FILME_ID, GENERO_ID) VALUES ('2', '3');
INSERT INTO FILME_GENERO (FILME_ID, GENERO_ID) VALUES ('3', '2');
INSERT INTO FILME_GENERO (FILME_ID, GENERO_ID) VALUES ('3', '3');
INSERT INTO FILME_GENERO (FILME_ID, GENERO_ID) VALUES ('4', '1');
INSERT INTO FILME_GENERO (FILME_ID, GENERO_ID) VALUES ('4', '2');

